### ISSUE TITLE
Public key

### ISSUE THREAD

**Issue by Clano21** [availproject/availup#10]
There is no public in my code

**Comment by prabal-banerjee** [comment]
Need more info

**Comment by Forbytex** [comment]
I can't locate the public key after running the node

**Comment by abdhilabs** [comment]
Just re-run the node, than you will see your public key

**Comment by Forbytex** [comment]
![Screenshot 2024-04-08 09 01 48](https://github.com/availproject/availup/assets/139140034/69ef6a93-a22d-4063-92d6-d56ae77bf650)
can you check this for me pls let me know what else I will do to get the public key I run on Linux
